feat/intial-v initial code

diff --git a/.github/workflows/publish-to-pypi.yml b/.github/workflows/publish-to-pypi.yml
--- a/.github/workflows/publish-to-pypi.yml
+++ b/.github/workflows/publish-to-pypi.yml
@@ -22,22 +22,20 @@ jobs:
         uses: actions/setup-python@v5.1.0
         with:
           python-version: 3.11
-
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
-          pip install build twine
+          if ! python -c "import twine" &> /dev/null; then
+              echo "twine not found, installing..."
+              pip install twine
+          fi
+          if ! python -c "import setuptools" &> /dev/null; then
+              echo "setuptools not found, installing..."
+              pip install setuptools
+          fi
 
-      - name: Build package
-        run: python -m build
+      - name: Build the package
+        run: python setup.py sdist
 
-      - name: Publish package
-        run: twine upload dist/*
-
-      - name: Add execute permissions to script
-        run: chmod +x scripts/publish.sh
-
-      - name: Publish package
-        run: |
-          chmod +x scripts/publish.sh
-          twine upload dist/* --non-interactive -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
+      - name: Publish the package
+        run: twine upload --repository-url https://upload.pypi.org/legacy/ -u __token__ -p ${{ secrets.PYPI_API_TOKEN }} dist/*
